name: Continuous Integration
on: [push] # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest # Sets the build environment a machine with the latest Ubuntu installed
    steps:
      - uses: actions/checkout@v4 # Adds a step to checkout the repository code

      - name: Build C# code
        run: dotnet build

      - name: Run C# tests
        run: dotnet test

      - name: build TS code
        working-directory: DotnetTemplate.Web
        run: npm ci && npm run build

      - name: run TS linter
        working-directory: DotnetTemplate.Web
        run: npm run lint

      - name: run TS tests
        working-directory: DotnetTemplate.Web
        run: npm t
